-- 투수 기록 테이블에 BSV/CG/SHO/QS/NH/PG 컬럼 추가

ALTER TABLE PLR_PTCH_GAME_REC
    ADD COLUMN BSV  TINYINT(1) NOT NULL DEFAULT 0 COMMENT '블론세이브' AFTER HLD,
    ADD COLUMN CG   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '완투'       AFTER BSV,
    ADD COLUMN SHO  TINYINT(1) NOT NULL DEFAULT 0 COMMENT '완봉'       AFTER CG,
    ADD COLUMN QS   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '퀄리티스타트' AFTER SHO,
    ADD COLUMN NH   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '노히트노런'  AFTER QS,
    ADD COLUMN PG   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '퍼펙트게임'  AFTER NH;

ALTER TABLE PLR_PTCH_MON_REC
    ADD COLUMN BSV  SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER HLD,
    ADD COLUMN CG   SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER BSV,
    ADD COLUMN SHO  SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER CG,
    ADD COLUMN QS   SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER SHO,
    ADD COLUMN NH   SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER QS,
    ADD COLUMN PG   SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER NH;

ALTER TABLE PLR_PTCH_SSNT_REC
    ADD COLUMN BSV  SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER HLD,
    ADD COLUMN CG   SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER BSV,
    ADD COLUMN SHO  SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER CG,
    ADD COLUMN QS   SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER SHO,
    ADD COLUMN NH   SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER QS,
    ADD COLUMN PG   SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER NH;

ALTER TABLE PLR_PTCH_TM_SSNT_REC
    ADD COLUMN BSV  SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER HLD,
    ADD COLUMN CG   SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER BSV,
    ADD COLUMN SHO  SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER CG,
    ADD COLUMN QS   SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER SHO,
    ADD COLUMN NH   SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER QS,
    ADD COLUMN PG   SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER NH;
